### ISSUE TITLE
solidity-parser-antlr outdated

### ISSUE THREAD

**Issue by area** [cgewecke/eth-gas-reporter#109]
I'm not 100% sure what is going on here, but trying to run a new version of `solidity-coverage` against [these contracts](https://github.com/wearekickback/contracts/tree/master/contracts) results in an error. `eth-gas-reporter` is unable to correctly pass an instrumented version of the contracts that contain `address payable owner = msg.sender`, despite the contract as a whole being valid solidity. Discovered in https://github.com/sc-forks/solidity-coverage/pull/318. Updating `solidity-parser-antlr` used in `eth-gas-reporter` solved the problem for me.

**Comment by cgewecke** [comment]
@area Ah thanks!

**Comment by cgewecke** [comment]
Fixed in 0.2.0 - thanks again :)
