### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/eth-gas-reporter#115]
- [x] Split everything up into files and use a folder.
- [x] Add comments, describe flow. Have no idea what's going on atm.
- [x] Expose sync hooks that let people improve report accuracy - esp if they're using contract dispatch tables. For example, EtherRouter users might be able to query the router to identify which contract is targeted for a given tx. Or add deployment detection using debug_trace etc.
- [x] Make truffle dependency optional. Should work with any pipeline tool that uses mocha and it should be simple to port this logic to other test runners. [buidler](https://github.com/nomiclabs/buidler) as a test case.
- [x] Run tests against geth

**Comment by alcuadrado** [comment]
Hey @cgewecke! 

I just noticed that you are going to test this project against Buidler. I'm not familiar with how this reporter works, but I'm happy to help.

**Comment by cgewecke** [comment]
Oh nice, thanks @alcuadrado.
