### ISSUE TITLE
Bump Mocha To Fix Security Vulnerability

### ISSUE THREAD

**Issue by simondlr** [cgewecke/eth-gas-reporter#132]
The version of Mocha used currently uses a package "diff" that has a security vulnerability. It was fixed, but Mocha needs to be updated to catch up with it.

Here's the fix in "diff": https://github.com/kpdecker/jsdiff/commit/2aec4298639bf30fb88a00b356bf404d3551b8c0

It's not serious/necessary fix, but just something to keep Github from screaming about security issues. :)

**Comment by cgewecke** [comment]
Hi @simondlr thanks.  

Published `0.2.1` which should fix this. Please lmk if not or you run into additional problems (there's been a bit of refactor here between this patch and the last.)
