### ISSUE TITLE
[Bug] NPM installation error: code ENOLOCAL (abi-decoder version)

### ISSUE THREAD

**Issue by bh2smith** [cgewecke/eth-gas-reporter#139]
## Problem Overview

Our [build](https://github.com/gnosis/dex-contracts/pull/136) is failing because of:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/eth-gas-reporter/node_modules/abi-decoder/node_modules/web3/bignumber.js@git+https:/github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2" as it does not contain a package.json file.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-06-24T18_32_33_404Z-debug.log
```

The error claims to be a missing `package.json` in `https:/github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2` but this is not true.

## Proposed Problem Source

It appears to be the commit [16bd5d7](https://github.com/cgewecke/eth-gas-reporter/commit/16bd5d79f25d1851a0b87e4a359cb3f26eb7fb7e) with abi-decoder version update that is causing this issue. 

## Suggested Fix

```bash
git revert 16bd5d79f25d1851a0b87e4a359cb3f26eb7fb7e
```

**Comment by cgewecke** [comment]
Hi @bh2smith thanks for reporting. Was able to get around this at gnosis dex CI by using `yarn` to install instead of npm. 

Will look into this further....

**Comment by cgewecke** [comment]
Labeling this `cannot reproduce` because installation from NPM with `npm install` seems to be working for the baseline cases I can think of. There *may* be something weird going on with the combination of deps at gnosis/dex-contracts, idk. 

Leaving open for additional reports - if anyone else sees this please weigh in.

**Comment by bh2smith** [comment]
Thanks @cgewecke  for looking into this. In the meantime I have dug into the [`abi-decoder` repo](https://github.com/ConsenSys/abi-decoder/) and discovered a [PR](https://github.com/ConsenSys/abi-decoder/pull/31) that bumps the web3 version as you suggested. I have also spoken with @denisgranha and he is ready to merge the PR once the appropriate changes are in place. If you like I can let you know once this has been taken care of and whether or not it helped with the original issue. 🍻

**Comment by cgewecke** [comment]
@bh2smith Oh nice, thanks for speaking to Denis and reviewing over there :)

**Comment by cgewecke** [comment]
`0.2.4` has the new decoder. Thanks for fixing!
