### ISSUE TITLE
Empty report with version > 0.2.1

### ISSUE THREAD

**Issue by ItsNickBarry** [cgewecke/eth-gas-reporter#148]
With the last few versions, my test report is simply empty:

```
·-----------------------|---------------------------|--------------|----------------------------·
|  Solc version: ----   ·  Optimizer enabled: ----  ·  Runs: ----  ·  Block limit: 6721975 gas  │
························|···························|··············|·····························
|  Methods              ·                1 gwei/gas                ·       256.90 eur/eth       │
·············|··········|·············|·············|··············|·············|···············
|  Contract  ·  Method  ·  Min        ·  Max        ·  Avg         ·  # calls    ·  eur (avg)   │
·------------|----------|-------------|-------------|--------------|-------------|--------------·

  51 passing (50s)
  10 pending
```

I'm not sure what details to provide to help find the cause of this.  Here's the `mocha` section of `truffle-config.js`:

```javascript
mocha: {
  reporter: 'eth-gas-reporter',
  reporterOptions: {
    showTimeSpent: true,
  },
},
```
For now, version `0.2.1` will suffice.

**Comment by cgewecke** [comment]
@ItsNickBarry Hmm - do you have any way I can repro this and look into it? The tests [here](https://travis-ci.org/cgewecke/eth-gas-reporter) are all normal.

**Comment by ItsNickBarry** [comment]
The repository I'm working is private at the moment, but I'll give you access if you want to take a look.

**Comment by cgewecke** [comment]
@ItsNickBarry Yes gladly, if you trust me.

**Comment by ItsNickBarry** [comment]
So, I updated Truffle and it seems to work now.  Thanks for your time.

**Comment by cgewecke** [comment]
@ItsNickBarry Oh great.
