### ISSUE TITLE
Wrap codechecks server calls in try/catch blocks

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/eth-gas-reporter#168]
See [gnosis-hg 58](https://github.com/gnosis/conditional-tokens-contracts/pull/58), 

[Travis error log](https://travis-ci.org/gnosis/conditional-tokens-contracts/jobs/565208024#L1453-L1463)

**Comment by cgewecke** [comment]
@krzkaczor Hi:) 

[gnosis/conditional-token-contracts](https://github.com/gnosis/conditional-tokens-contracts/pull/58) is using codechecks w/ gas-reporter and getting a 500 server error (on the `.success` step I think). Can you see anything in the server logs on your side about this?

```
3.87s$ npx codechecks
CodeChecks Client v.0.1.5
https://codechecks.io
Executing 1 codechecks files
Base branch: d7ba7a2f
Executing codechecks.yml...
Error occured:  500 - {"statusCode":500,"message":"Internal server error"}
```

It possible I broke something on my side but am getting normal results in all my tests here...

**Comment by krzkaczor** [comment]
Hey!
I am on it. Generally, it's related to the fact that once in a while GitHub API is not accessible. 

I hope that today I will come up with good error handling/retry strategy. I will keep you posted.

**Comment by cgewecke** [comment]
@krzkaczor Ah cool! Thanks!

**Comment by krzkaczor** [comment]
I **just** pushed the fix (and improved logging ;)) to production. Could you let me know if it helps @cgewecke

**Comment by cgewecke** [comment]
Yes I will, thanks so much @krzkaczor!

Closing here because resolved by #170 / `0.2.9`

**Comment by cgewecke** [comment]
@krzkaczor In the end gnosis's problem might be that they [renamed their repo](https://github.com/gnosis/conditional-tokens-contracts/pull/61#issuecomment-517032563). Idk, anyway it works again now after turning project on/off in the codechecks UI.  

Thanks again for looking into this...

**Comment by krzkaczor** [comment]
@cgewecke fyi: i deployed multiple stability fixes over the weekend — random 500s should be gone now.

**Comment by cgewecke** [comment]
Thanks @krzkaczor!
