### ISSUE TITLE
Husky dependency somehow added a bunch of .git hooks

### ISSUE THREAD

**Issue by HarryR** [cgewecke/eth-gas-reporter#169]
The Husky dependency used by eth-gas-reporter somehow added a bunch hooks into my Git repository.

I do not want hooks silently installed, modified, deleted or otherwise messed with. This is malicious behaviour. **DO NOT SILENTLY MESS WITH PEOPLES GIT REPOSITORIES VIA A THIRD-PARTY DEPENDENCY.**

Seriously... wtf?

**Comment by cgewecke** [comment]
@HarryR Very sorry about this. It's a [dev dependency here](https://github.com/cgewecke/eth-gas-reporter/blob/master/package.json#L62) - not quite sure how or why it's installing git hooks in your project but will investigate. 

Can you provide a little more info about:
+ version ?
+ installation method?

**Comment by cgewecke** [comment]
@HarryR I've just installed the reporter (as a dev dependency) using both npm and yarn and husky doesn't appear as an added dependency. 

We *were* using npm shrinkwrap here for a bit (until a couple weeks ago) to remove a sec vuln in one of our deps - it's possible behavior was different then.

**Comment by HarryR** [comment]
I was using eth-gas-reporter 0.2.4, and upgraded the dependency to 0.2.8.

At the time I had removed the local node_modules directory and re-installed everything a handful of times while trying to see if there was a non-buggy version of Truffle. I don't know exactly when, I wasn't doing anything more than just `npm install` etc. and tweaking my own `packages.json` - at no point did I include Husky in my repository.

I started getting error messages when I tried to do a Git commit about Husky not being installed, which was preventing me from doing a git commit.

Then I saw this:
```
$ cat .git/hooks/
applypatch-msg             post-update                pre-rebase.sample
applypatch-msg.sample      post-update.sample         pre-receive
commit-msg                 pre-applypatch             pre-receive.sample
commit-msg.sample          pre-applypatch.sample      prepare-commit-msg
post-applypatch            pre-auto-gc                prepare-commit-msg.sample
post-checkout              pre-commit                 push-to-checkout
post-commit                pre-commit.sample          sendemail-validate
post-merge                 pre-push                   update
post-receive               pre-push.sample            update.sample
post-rewrite               pre-rebase                 
laptop:ethsnarks nomad$ cat .git/hooks/pre-push
#!/bin/sh
# husky

# Hook created by Husky
#   Version: 2.3.0
#   At: 30/07/2019, 16:11:49
#   See: https://github.com/typicode/husky#readme

# From
#   Directory: /Users/nomad/Projects/ethsnarks/node_modules/eth-gas-reporter/node_modules/husky
#   Homepage: https://github.com/typicode/husky#readme

scriptPath="node_modules/eth-gas-reporter/node_modules/husky/run.js"
hookName=`basename "$0"`
gitParams="$*"

debug() {
  [ "${HUSKY_DEBUG}" = "true" ] || [ "${HUSKY_DEBUG}" = "1" ] && echo "husky:debug $1"
}

debug "$hookName hook started..."

if ! command -v node >/dev/null 2>&1; then
  echo "Info: Can't find node in PATH, trying to find a node binary on your system"
fi

if [ -f "$scriptPath" ]; then
  # if [ -t 1 ]; then
  #   exec < /dev/tty
  # fi
  if [ -f ~/.huskyrc ]; then
    debug "source ~/.huskyrc"
    . ~/.huskyrc
  fi
  node_modules/eth-gas-reporter/node_modules/run-node/run-node "$scriptPath" $hookName "$gitParams"
else
  echo "Can't find Husky, skipping $hookName hook"
  echo "You can reinstall it using 'npm install husky --save-dev' or delete this hook"
fi
```

**Comment by HarryR** [comment]
I'll keep an eye on it, maybe I had only noticed it now, and it happened at some point in the past?

It got me really worried, I don't like it when stuff like this happens.

**Comment by cgewecke** [comment]
Yeah that's awful. I'm really sorry.

**Comment by HarryR** [comment]
On some happier news, I love this project, aside from the thing above... 

Why doesn't Truffle have gas reporting as standard? That's what matters, rather than milliseconds.

✋ thanks for making it, I appreciate it

**Comment by cgewecke** [comment]
Thanks @HarryR :) Very sweet of you.
