### ISSUE TITLE
Codecheck internal error

### ISSUE THREAD

**Issue by boolafish** [cgewecke/eth-gas-reporter#184]
Hi, starting today, our CI suddenly starts to fail the step that is doing code check and get internal error.

Here is one example that failed: https://app.circleci.com/jobs/github/omisego/plasma-contracts/3242

Here is another example that does not failed however still do have the internal error message and asks us to report to this repo: https://app.circleci.com/jobs/github/omisego/plasma-contracts/3236

```
Executing 1 codechecks files
Base branch: 89e8194c

Executing plasma_framework/codechecks.yml...

If you have a chance, report this incident to the eth-gas-reporter github issues.
Codechecks errored running 'success'...
StatusCodeError: 500 - {"statusCode":500,"message":"Internal server error"}
```

**Comment by cgewecke** [comment]
@boolafish I've just published `0.2.12` which should prevent codechecks exceptions from throwing errors in your CI. 

However, it's possible that codecheck's server goes down occasionally or their Github hook doesn't work. In those cases you may see incorrect diff data in your gas chart. 

Apologies for this and thanks for reporting.

**Comment by boolafish** [comment]
Thanks for your prompt help!! I think it solved my issue :)

I see, so this incident is actually some occasional failure from dependency server? Can I also get some more understanding that in those cases, the gas chart would be using whatever saved last time? or how it would be incorrect as you mentioned?

(I will leave this issue close by you as I am not sure if you're using this to track anything more on your side or not.)

**Comment by cgewecke** [comment]
@boolafish Yes there are calls made to an external codechecks server at different stages in the CI cycle, and exactly how it executes varies by CI service. (It's a bit confusing tbh.) As written, if any of these calls fail, the check should exit with code 0 and not report in the Github UI.

The diff comparison is made vs data previously saved for the branch/commit the PR is being merged into.  So *if* there's a codechecks failure on a PR and you merge anyway, it means future diffs will be against an older baseline. Eventually this will self-correct as you merge PRs with gas checks that worked.  Idk if that makes sense. 

I'm going to close here and will talk to the Codechecks team about why these server calls failed - they might be able to see your runs in their backend. I suspect it's just that something was down for a bit.
