### ISSUE TITLE
Calls of methods containing tuple arguments are not counted

### ISSUE THREAD

**Issue by jo-es** [cgewecke/eth-gas-reporter#186]
I've setup `eth-gas-reporter` for our codebase and noticed that it does not recognize methods with arguments of type tuple as being called. If `onlyCalledMethods` is set to false they are listed in the reporting table but without any results (# calls is 0). 
For example in the following [test-case](https://github.com/atpar/ap-monorepo/blob/master/packages/ap-contracts/test/Core/TestAssetRegistry.js#L91) only `setEventId` is counted in the [reporting](https://travis-ci.org/atpar/ap-monorepo/builds/590359855#L475).

**Comment by cgewecke** [comment]
@jo-es Interesting! (And strange) ... will investigate, thanks for reporting.

**Comment by MariusVanDerWijden** [comment]
@cgewecke I have the same problem. It does calculate their gas costs correctly before (the number after the test case), but does not display them in the reporting table

**Comment by cgewecke** [comment]
@MariusVanDerWijden @jo-es 

Believe the underlying issue is at [consensys/abi-decoder](https://github.com/ConsenSys/abi-decoder/issues/30#issuecomment-459933093), which this lib uses to calculate the function signature hashes of contract methods. Those hashes are how the reporter identifies which method was called when inspecting a transaction's input. 

Will look at ethers.js and see if it exposes a more modern encoder/decoder to resolve this....

**Comment by boolafish** [comment]
+1 on this. Failed to get report on functions using struct with abi decoder v2

**Comment by cgewecke** [comment]
Apologies for the delay fixing this. Should now be resolved in `0.2.13` - migrated decoding to ethers.js.

**Comment by cgewecke** [comment]
Ethers is crashing plasma unfortunately...

**Comment by boolafish** [comment]
sigh....I tracked a little bit and seems like `ether` cannot read function taking contract as args.

It was failing at contract `PaymentChallengeIFEInputSpent`, and the function `buildController` takes `PlasmaFramework` as the first arg. It would not read that as type `address` but as type `PlasmaFramework` and then throws the error as it is undefined type.

**Comment by cgewecke** [comment]
@boolafish It works with ethers@next, will upgrade the dep and publish in the next hour or so unless there are weird problems with it...

**Comment by cgewecke** [comment]
@boolafish `0.2.14`. Tested plasma locally and looks like +/- like this... image is not the whole chart but seems like there are more PaymentExitGame methods reported than in yesterday's codechecks ... just lmk if this still isn't right.

![Screen Shot 2019-12-02 at 9 38 25 PM](https://user-images.githubusercontent.com/7332026/70023764-3ee3c100-154d-11ea-9983-480ae4e4114c.png)

**Comment by boolafish** [comment]
Thanks for the speedy respond and fix !! :)
