### ISSUE TITLE
Unit test gas costs should exclude test harness setup cost

### ISSUE THREAD

**Issue by elenadimitrova** [cgewecke/eth-gas-reporter#2]
Gas costs for each unit test should not include the gas spent on setting up the test harness in `before` and `beforeEach` hooks.

**Comment by cgewecke** [comment]
@elenadimitrova! Thank you, yes that's clearly correct.

**Comment by cgewecke** [comment]
Should be fixed in `0.0.4`. Thanks again for reporting :)
