### ISSUE TITLE
Display gas cost for inherited functions

### ISSUE THREAD

**Issue by Wolf-Rost** [cgewecke/eth-gas-reporter#200]
Hey, 
thank you for creating such a great module.
In my recent test suite, I stumbled across a problem when it comes to seeing the gas costs of inherited functions. 
Would it be possible to see the gas costs of inherited functions in the table as well?

**Comment by cgewecke** [comment]
@Wolf-Rost Thanks so much!

Could you give an example an "inherited" function which doesn't appear in the table as it should?

We have some unit tests for this case which look ok....:
https://github.com/cgewecke/eth-gas-reporter/blob/6e9b297ae2c1228ee52c7200947e4851f1d1959f/mock/contracts/VariableCosts.sol#L6

.. can be seen reporting VariableCosts.transferPayment (a wallet method)  [in TravisCI here][1]

Is it possible the inherited method is never used? The reporter hides methods that never get called by default - this can be disabled by setting `onlyCalledMethods: true` in the config.

[1]: https://travis-ci.org/github/cgewecke/eth-gas-reporter/jobs/659892942#L1484

**Comment by Wolf-Rost** [comment]
I further investigated the problem and come to the conclusion that the inherited functions are shown as you said. The functions that are not shown are the ones that I call through a proxy call.

I use the following proxy function to make calls to other contracts:

```
fallback()
        external
    {
        assembly {
            let ptr := mload(0x40)  // Get free memory pointer
            let _len := sub(calldatasize(), 32) // Subtract 32 bytes from the calldatasize because the first 32 bytes are the destination address
            calldatacopy(ptr, 32, _len) // Copy the remaining bytes to memory at the position of the free memory pointer
            let status := call(gas(), calldataload(0x0), callvalue(), ptr, _len, 0, 0)  // Call the external method at the destination address with the remaining call data
            let size := returndatasize()
            returndatacopy(ptr, 0, size)

            let value := mload(ptr)
            sstore(0, value)

            switch status
            case 0 { revert(ptr, size) }
            default { return(ptr, size) }
        }
    }
```

In my tests I call the method as shown below:
```
await proxyMultiSigAdmin.sendTransaction(
            Utils.getTxData(
                mockRegistryManager.address,
                mockRegistryManager.contract.methods.updateRegistry(
                    assetManagerAddress,
                    4,
                    false
                )
            )
        );
```

What I expected was that the gas costs for the updateRegistry function were shown in the table.
However, I think the eth-gas-reporter can not "see" the call in assembly to the updateRegistry function as I just provide the call to updateRegistry as byte data, right?

**Comment by cgewecke** [comment]
@Wolf-Rost Yes, that's correct - proxy calls are often hidden.

However, it *is* possible to define resolution rules for proxies - more info about that here:
+ [resolving method identities when using proxy contract][1]

[1]: https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/advanced.md#resolving-method-identities-when-using-proxy-contracts

Unfortunately, the `fallback` and `receive` syntax remain problematic here so this will only work in solc 0.5.x.

**Comment by Wolf-Rost** [comment]
Yes, the receive function is still a problem but without one, a resolver for my proxy works like a charm.
Thank you @cgewecke !
