### ISSUE TITLE
Upgrade mocha dependency

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/eth-gas-reporter#203]
Mocha 5 is afflicted by the minimist vuln warning :/
Mocha 6 has breaking changes...

**Comment by alcuadrado** [comment]
This is very interesting, Chris. I didn't know where the warning was coming from. 

I think we'll also have to upgrade it in Buidler. @tmilar has already reviewed the breaking changes introduced in v6 and v7, and IIRC they aren't significant. Is this right, Tomi?

**Comment by tmilar** [comment]
Hi guys, yes I've reviewed the changelist of mocha v6 and v7 a few weeks ago, and arrived to the conclusion that there shouldn't be any issue with upgrading to latest v7 in buidler. 
I can check it out again if you want, and if everything is smooth, send a PR.

**Comment by alcuadrado** [comment]
Now that I think about it, this project may use different parts of Mocha's
api.

Should we coordinate an upgrade between this project, buidler and truffle?

**Comment by cgewecke** [comment]
@alcuadrado @tmilar Yes, happy to coordinate.

Last summer there [was something][1] about v6 that crashed the reporter. Will need to see if that's still happening on either 6 or 7 and address it. 

I'll open an exploratory PR this evening.
 
[1]: https://github.com/trufflesuite/truffle/pull/2113#issuecomment-505130747

**Comment by cgewecke** [comment]
Upgraded to Mocha 7.

**Comment by cgewecke** [comment]
@alcuadrado @tmilar Do either of you have reservations about upgrading to Mocha 7? 

Am not seeing any problems in the E2E tests here and the breaking changes from [release notes][1] across 6 and 7 seem like they might not affect many people...idk.

Am comfortable releasing the change here as a patch fwiw.  

[1]: https://github.com/mochajs/mocha/releases

**Comment by cgewecke** [comment]
`0.2.17`
