### ISSUE TITLE
Doesn't seem to register method calls on Buidler starter project

### ISSUE THREAD

**Issue by jtremback** [cgewecke/eth-gas-reporter#207]
I started a new Buidler project using their default project called "greeter" which just writes and reads from a contract storage variable. The gas reporter doesn't seem to register that the methods called by the test were called

```
$ npx buidler test
All contracts have already been compiled, skipping compilation.

  Greeter
Deploying a Greeter with greeting: Hello, world!
Changing greeting from 'Hello, world!' to 'Hola, mundo!'
    ✓ Should return the new greeting once it's changed

·----------------------------|----------------------------|-------------|----------------------------·
|    Solc version: 0.6.6     ·  Optimizer enabled: false  ·  Runs: 200  ·  Block limit: 9500000 gas  │
·····························|····························|·············|·····························
|  Methods                   ·                5 gwei/gas                ·       206.50 usd/eth       │
·············|···············|··············|·············|·············|·············|···············
|  Contract  ·  Method       ·  Min         ·  Max        ·  Avg        ·  # calls    ·  usd (avg)   │
·············|···············|··············|·············|·············|·············|···············
|  Greeter   ·  greet        ·           -  ·          -  ·          -  ·          0  ·           -  │
·············|···············|··············|·············|·············|·············|···············
|  Greeter   ·  setGreeting  ·           -  ·          -  ·          -  ·          0  ·           -  │
·------------|---------------|--------------|-------------|-------------|-------------|--------------·

  1 passing (2s)
```

**Comment by cgewecke** [comment]
Hi @jtremback 

We're running a buidler greeter example in CI for the buidler plugin version ([buidler-gas-reporter][1]) and it's working, with caveats.

If you're using buidlerevm, you have to launch the client as an independent node and specify  `localhost` via a network cli option, e.g

```
npx buidler node > /dev/null &
npx buidler test --network localhost
```

There's more on this topic [here][2].

Does that resolve things for you? If not just lmk how you're setting things up etc.

[1]: https://github.com/cgewecke/buidler-gas-reporter
[2]: https://github.com/cgewecke/buidler-gas-reporter#using-buidlerevm-warning

**Comment by jtremback** [comment]
Thanks! I wasn't using the `--network localhost` option. Sorry for the dumb question.

**Comment by cgewecke** [comment]
@jtremback Oh no worries! Sorry about the docs, thanks for flagging that.

**Comment by jtremback** [comment]
The buidler [docs](https://buidler.dev/plugins/buidler-gas-reporter.html) are actually wrong, but I have raised an issue with them.
