### ISSUE TITLE
Add option to exclude intrinsic gas cost

### ISSUE THREAD

**Issue by adlerjohn** [cgewecke/eth-gas-reporter#214]
Gas reported currently includes the 21,000 intrinsic gas cost for all transactions. There should be an option to exclude this cost, since it may not always be meaningful for analysis.

**Comment by cgewecke** [comment]
Hi @adlerjohn, thanks for suggesting.

Could you explain this idea a bit more? How would excluding the 21000 make analysis more meaningful?

**Comment by adlerjohn** [comment]
If I have a library, and I want to know how much gas a pure function uses over some input values, I only care about the non-intrinsic gas cost.

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

In the latest version at Hardhat, this is supported by toggling the `includeIntrinsicGas` option to `false` 

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
