### ISSUE TITLE
Setting 'artifactType' breaks the gas report

### ISSUE THREAD

**Issue by PaulRBerg** [cgewecke/eth-gas-reporter#226]
## Description

Setting any value to `artifactType`, even a correct value like "truffle-v5" or "buidler-v1", breaks the gas report:

<img width="704" alt="Capture d’écran 2020-10-20 à 20 00 10" src="https://user-images.githubusercontent.com/8782666/96619433-dd684480-130e-11eb-97ce-65ec3fd893b5.png">

## Steps to Reproduce

1. Fork [mainframe-lending-protocol][1]
2. Switch to the [gasReporterBug](https://github.com/MainframeHQ/mainframe-lending-protocol/tree/gasReporterBug) branch
3. Install dependencies with yarn 
4. Uncomment "artifactType" line in `buidler.config.ts`
5. Run tests via `yarn run` (don't worry, I set `.only` on a describe so that it doesn't take long)

## Environment

+ @nomiclabs/buidler@1.4.7
+ buidler-gas-reporter@0.1.4
+ eth-gas-reporter@0.2.18

[1]: https://github.com/MainframeHQ/mainframe-lending-protocol

**Comment by PaulRBerg** [comment]
It possibly has to do with this line:

https://github.com/cgewecke/buidler-gas-reporter/blob/master/src/index.ts#L75

**Comment by cgewecke** [comment]
@PaulRBerg 

What are you trying to do when using this setting? The docs on this aren't super clear (sorry) but the core idea is that you *could* write a method which translates the artifact format of the development platform you're working with into something the reporter can process. 

For buidler this is already done as part of `buidler-gas-reporter` [here][1] 

[1]: https://github.com/cgewecke/buidler-gas-reporter/blob/02a2fbe36765477e5bb329e9cdc181c88e252750/src/index.ts#L32-L47

**Comment by PaulRBerg** [comment]
I'm not trying to achieve anything in particular except get myself familiar with the API and run the gas reporter.

In the README, it says that "artifactType" is either a function or a string. I went with the latter and the value in the "gasReporter" config in `buidler.config.ts`, but it broke the gas report.

**Comment by cgewecke** [comment]
@PaulRBerg 

Yes tbh it's not really meant to be used with buidler. 

Was added mostly to try to help address #128 and make buidler-gas-reporter-like integrations possible. 

Thanks for finding this...it's not very well explained.

**Comment by PaulRBerg** [comment]
Happy to help. Sorry, I guess I should've opened this in the `buidler-gas-reporter` repo instead.

**Comment by cgewecke** [comment]
Hi! eth-gas-reporter is being deprecated in favor of hardhat-gas-reporter.

In the latest version at Hardhat, `artifactType` has been removed (it's just an HH plugin now).

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
