### ISSUE TITLE
@codechecks/client should be dev dependency

### ISSUE THREAD

**Issue by cruzdanilo** [cgewecke/eth-gas-reporter#229]
currently, `@codechecks/client` is a peer dependency, which causes warnings on npm/yarn install when not being used.

**Comment by cgewecke** [comment]
Hi! eth-gas-reporter is being deprecated in favor of hardhat-gas-reporter.

In the latest version at Hardhat, Codechecks support has been removed because they haven't been accepting new users for a while.

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
