### ISSUE TITLE
Gas is not reported for non-default Signers when using hardhat/ethers

### ISSUE THREAD

**Issue by nmclrn** [cgewecke/eth-gas-reporter#235]
I am using hardhat with ethers and waffle and hardhat-gas-reporter. It's generally awesome! 👏 👏 

If I have a test that calls:
`await myContract.connect(someNonDefaultSigningAccount).myFunction(someParams)`
I see no gas usage reported for this function call.

The problem here seems to be related to calling [connect](https://docs.ethers.io/v5/api/contract/contract/#Contract-connect) to use a different Signer, because calling
`await myContract.myFunction(someParams)` (without the `.connect()`) reports gas just fine.

**Comment by cgewecke** [comment]
Hi @nmclrn 

To double-check, are you using the latest version (`1.0.4`)? (It was published last week).

A similar issue was fixed in that release via [hardhat-gas-reporter 54][1].


[1]: https://github.com/cgewecke/hardhat-gas-reporter/pull/54

**Comment by nmclrn** [comment]
Upgrading to 1.0.4 fixes this - thank you so much for the super-quick reply!
