### ISSUE TITLE
Add option to make output "markdown compatible"

### ISSUE THREAD

**Issue by Amxx** [cgewecke/eth-gas-reporter#236]
The report table, while it looks like markdown, is not markdown. I believe it would be very nice to be able to display report either in github or through modia that support markdown formating.

**Comment by cgewecke** [comment]
@Amxx 

Agree this is a good idea. 

The tool already produces a (partial) [markdown formatted table for its codechecks feature][1]. 

[1]: https://github.com/cgewecke/gas-check/pull/36/checks

(Unfortunately the codechecks service looks like it's temporarily disabled new users..)

**Comment by cgewecke** [comment]
Hi! eth-gas-reporter is being deprecated in favor of hardhat-gas-reporter.

In the latest version at Hardhat, it's possible to select `"markdown"` as one of the `reportFormat` options 

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
