### ISSUE TITLE
hardhat_reset interferes with gas reporter

### ISSUE THREAD

**Issue by jtremback** [cgewecke/eth-gas-reporter#244]
Using the "hardhat_reset" request seems to break eth-gas-reporter. I have defined this function:

```
async function resetChain() {
  await network.provider.request({
    method: "hardhat_reset",
    params: [],
  });
}
```

And i call it like this: `await resetChain();` on the first line of each test case. I am using Hardhat, with hardhat-waffle, and chai assertions.

When I comment out the call to hardhat_reset, full gas reporting works. Also, if I restart the evm by hand (ending and restarting the evm process in the terminal), the first time I run the tests again, even with hardhat_reset, gas reporting works. This gives me the hunch that there may be some kind of race condition in the setup.

**Comment by cgewecke** [comment]
Hi @jtremback. Thanks for reporting!

I think the problem might originate in this PR: https://github.com/nomiclabs/hardhat/pull/1024 which fixes a bug with the Ethers provider.

If that's the case, a possible solution is to duplicate [the proxy provider][1] logic there in hardhat-gas-reporter's [provider wrapper, here][2]

[1]: https://github.com/nomiclabs/hardhat/pull/1024/files#diff-426be0aa67ff17d3167ae9666479f491be1882b95c9d31e6794a71406472a05dR14-R28 
[2]: https://github.com/cgewecke/hardhat-gas-reporter/blob/97258f99e9a7d6bfa1852363e7ba92beb20f64f3/src/providers.ts#L7-L14

**Comment by jtremback** [comment]
Hmmm very interesting. Thanks!

**Comment by jtremback** [comment]
It looks like the chain state is reset at some point when running tests without calling this method. So I think I can do without this functionality for now and probably won't make the recommended changes at this point.
