### ISSUE TITLE
Compare two different implementations of the same smart contract

### ISSUE THREAD

**Issue by vrde** [cgewecke/eth-gas-reporter#245]
I have two different implementations of an ERC-721 token, and I'd like to compare the gas usage method by method (the have the same interface). I was thinking to run the same test suite on the two implementations, and output the gas report to a json file. Then write some code to display the differences in gas usage and integrate it with hardhat.

I found [it's possible to output a json](https://github.com/cgewecke/eth-gas-reporter/blob/23fc57687b4e190c7e28571a14773d96cdbf7d63/docs/gasReporterOutput.md), but I don't know where to start, do you have any ideas?

**Comment by cgewecke** [comment]
Hi @vrde,

Yes! Someone made a similar project as part of a CS masters thesis, published to npm here:

https://www.npmjs.com/package/scenario-eth-gas-reporter

This was a while ago, so it's not integrated with hardhat.... but adapting/borrowing pieces of that might be a quick route to what you're looking for. 

**Example Output**

![exampleoutput](https://user-images.githubusercontent.com/7332026/113362995-90988900-9304-11eb-97eb-a5137d24f981.jpg)

**Comment by vrde** [comment]
@cgewecke thanks for your prompt reply! It's exactly what I'm looking for.
