### ISSUE TITLE
enabled but does not report anything

### ISSUE THREAD

**Issue by nazariyv** [cgewecke/eth-gas-reporter#246]
<img width="600" alt="gas-reporter" src="https://user-images.githubusercontent.com/13678461/113431048-1125bb00-93d3-11eb-8daa-9b278efab857.PNG">

what might be the cause of this? thank you

**Comment by cgewecke** [comment]
@nazariyv It's impossible to know without reproduction steps. Can you create an example repo which results in the same output and open it on github?

**Comment by cgewecke** [comment]
@nazariyv Have you used Paul Bergs [solidity-template][1] for your project? 

If so, it has a bug in the gasReporter config that results in no data being produced. 

[This line in the config][2], where `excludeContracts` has an empty string should be commented out (or given a non-empty string if you want to skip something.)

[1]: https://github.com/paulrberg/solidity-template
[2]: https://github.com/paulrberg/solidity-template/blob/b70050d4ded3512ca1a484f3d594498c81637b88/hardhat.config.ts#L61

**Comment by nazariyv** [comment]
I have used this:

https://github.com/wighawag/template-ethereum-contracts

This is my config:

```
  paths: {
    sources: 'src',
  },
  gasReporter: {
    currency: 'USD',
    gasPrice: 200,
    coinmarketcap: process.env.COINMARKETCAP_API_KEY,
    maxMethodDiff: 10,
  }
```

**Comment by cgewecke** [comment]
@nazariyv When I clone that template, install and run `yarn gas`, per the instructions I see:

![Screen Shot 2021-04-02 at 2 17 19 PM](https://user-images.githubusercontent.com/7332026/113455074-93f04b00-93be-11eb-841b-d405b4626d67.png)

**Comment by jfrank-summit** [comment]
I am also having this issue after adding gas-reporter to an existing project. were you able to get it resolved @nazariyv ?

**Comment by Magicking** [comment]
Having the same problem here, using the specified template above, after a bit of investigation, it seems that the `EGRDataCollectionProvider` provider is not called upon request, in the process of writing a minimal test case

**Comment by cgewecke** [comment]
Closing, please just ping if this is still an issue.

**Comment by Magicking** [comment]
Sorry I have not updated here, got busy elsewhere, long story short, wrote 3 different tests cases that I can't share unfortunately but I did not manage to find the minimum, my best guess as of today is an incomparability between hardhat community plugins!
