### ISSUE TITLE
Methods not showing on report pure math operation functions 

### ISSUE THREAD

**Issue by echojoel** [cgewecke/eth-gas-reporter#248]
Hi, 

I am trying to estimate the gas cost of complex mathematical operations on solidity. 
I've included a sub-set of the project in this repo : https://github.com/Joelpo/gas-reporter-test

[Report](https://ibb.co/1mn4Y64)

I'd like to know the gas cost of calling each of these functions tested in the test, but the functions are not showing on the report. 

Dependencies : 
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@types/mocha": "^8.2.2",
    "chai": "^4.3.4",
    "eth-gas-reporter": "^0.2.22",
    "ethereum-waffle": "^3.4.0",
    "hardhat": "^2.4.1",
    "hardhat-gas-reporter": "^1.0.4",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.5"

To reproduce : 
git clone https://github.com/Joelpo/gas-reporter-test
yarn test

Any ideas on how to solve this?

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

This is supported via the `reportViewAndPureMethods` option in the latest hardhat version

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
