### ISSUE TITLE
Allow to remove phone homes

### ISSUE THREAD

**Issue by fulldecent** [cgewecke/eth-gas-reporter#249]
Currently there appear to be two phone-homes in this project:

1. Get ETH price
2. Get gas price

I would like an option to remove both of these.

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

This is supported in the latest hardhat version

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
