### ISSUE TITLE
Allow to not show currency

### ISSUE THREAD

**Issue by fulldecent** [cgewecke/eth-gas-reporter#250]
Currently, you can pass several currency options in or leave blank for the default of EUR.

I would like to pass in "NONE", "", or null and not get any currency amounts.

This should also disable any need to fetch gas prices.

Implementing this is one way to resolve #249 

---

My motivation for this issue is that prices are useless. They change too fast and I don't care about them. The price denominated in `gas` is useful and mostly context insensitive so it is much more helpful.

But also, again, why phone home if not needed...

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

The latest version at Hardhat has an `offline` option and by default doesn't fetch data unless a coinmarketcap API key is provided. You can hardcode a gwei gas price with the `gasPrice` option and set the `tokenPrice` option to "1" to get prices denominated in network token.   

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
