### ISSUE TITLE
Solidity parser doesn't support new Solidity features

### ISSUE THREAD

**Issue by TomiOhl** [cgewecke/eth-gas-reporter#253]
When I use [custom errors introduced in Solidity 0.8.4](https://blog.soliditylang.org/2021/04/21/custom-errors/), I get the following error:
![error](https://user-images.githubusercontent.com/6696659/129587035-80dc9f03-a0b3-436c-bc1f-358a638fa624.png)
Apparently it's solved in the latest version of @solidity-parser/parser. Ive tested with 0.13.3-rc.1.
So that dependency needs to be updated to keep compatibility with new Solidity codes.

**Comment by enzoferey** [comment]
Any update on this one ?

**Comment by TomiOhl** [comment]
@cgewecke can you please look into this? A simple `npm update` would fix this (and also other issues like #252) and since cgewecke/hardhat-gas-reporter also depends on this it will fix the issue there too

**Comment by TomiOhl** [comment]
Fixed in #261, thanks
