### ISSUE TITLE
Table is generated before gasPrice and ethPrice are fetched

### ISSUE THREAD

**Issue by markmiro** [cgewecke/eth-gas-reporter#254]
# Summary
The reporter doesn't wait for the results to come back before printing them out.

I spent $70 on a deploy of a couple toy contracts, so I think it would be helpful to have this information even for the simplest contracts.

# Explanation
See the last column? It should have price data, but it doesn't show it even after following the docs.
<img width="708" alt="Screen Shot 2021-08-16 at 2 45 36 PM" src="https://user-images.githubusercontent.com/1214630/129633432-dc25a7a8-9cca-48fb-85d2-22619c912dad.png">

Docs that say I should add my own `coinmarketcap` API key:
<img width="851" alt="Screen Shot 2021-08-16 at 2 47 18 PM" src="https://user-images.githubusercontent.com/1214630/129633581-09a24624-a9e8-4ec4-8204-3043970ae13d.png">

So I updated my reporter:
```js
{
  gasReporter: { coinmarketcap: 'd25b5576-a4ee-41be-bb2b-aca2ba3ae5d8' }
}
``` 
Note: above key is from [eth-gas-reporter/lib/config.js](https://github.com/cgewecke/eth-gas-reporter/blob/23fc57687b4e190c7e28571a14773d96cdbf7d63/lib/config.js#L12) because I don't want to show mine.

I was expecting the issue to get resolved but it didn't work. However, adding custom `gasPrice` did work:
```
{
  gasReporter: { coinmarketcap: '...', gasPrice: 30 }
}
```

That's when I tried to look into this repo's implementation. I see that the [index.js](https://github.com/cgewecke/eth-gas-reporter/blob/master/index.js) file in this mocha reporter is fetching price information when it's being initialized.

# Solutions
I tried to look into how to fix this and I honestly don't know.

The problem is with this line:
https://github.com/cgewecke/eth-gas-reporter/blob/master/index.js#L53

There has to be a way to wait until this async function is done, but I haven't found a way.

People [have tried](https://github.com/mochajs/mocha/issues/812) to do some async stuff for mocha reporting, but this issue doesn't help here.

I spent $70 on a deploy of a couple toy contracts, so I think it's great to know.

# Workaround
The best solution is to add a dummy test like this:
```js
// Wait so the reporter has time to fetch and return prices from APIs.
// https://github.com/cgewecke/eth-gas-reporter/issues/254
describe("eth-gas-reporter workaround", () => {
  it("should kill time", (done) => {
    setTimeout(done, 2000);
  });
});
```

**Comment by alxiong** [comment]
same issue encountered, the workaround ☝️, tho hacky, does works for me as well. So please fix this bug. @cgewecke 
Thanks!

**Comment by cgewecke** [comment]
Unfortunately there isn't a trivial fix for this that I know of. Mocha's 3rd party reporter API hooks are synchronous. 

It could be fixed for hardhat-gas-reporter though, that has async task hooks which run before the reporter loads.

**Comment by TheMarvelousWhale** [comment]
> 
> 
> same issue encountered, the workaround ☝️, tho hacky, does works for me as well. So please fix this bug. @cgewecke Thanks!

Hi Alex would you like to update the boilerplater tutorial as well TvT maybe suggest them to modify the index.js in eth-gas-reporter?

**Comment by cgewecke** [comment]
This is fixed at hardhat-gas-reporter but cannot be fixed here (at the mocha reporter level) due to mocha's synchronous hook design.

Closing
