### ISSUE TITLE
How do I get the report to display nicely like it is on the npm site 

### ISSUE THREAD

**Issue by thedarkjester** [cgewecke/eth-gas-reporter#260]
Is there a way to get the report to display nicely? is there a particular viewer used?

I didn't see a questions tab :(

**Comment by cgewecke** [comment]
@thedarkjester What are you seeing? Could you post a screenshot?

It might be helpful if you gave some info about your operating system etc...

**Comment by thedarkjester** [comment]
I am on Windows, and just opening it in visual studio code - but I am assuming that isn't the best place to view it.

VS Code view

![image](https://user-images.githubusercontent.com/3957173/141209169-4ce5b5a1-f52e-492b-aebf-783da52de626.png)

Browser View:

![image](https://user-images.githubusercontent.com/3957173/141209214-eaa09c41-17fd-407f-875a-74f9677d1b0a.png)

**Comment by cgewecke** [comment]
Yes, by default it's meant to print to the console at the command line. 

You might get a cleaner result in VisualStudio if you set the [noColors option][1] to true. I think some of the noise in your display is console colorization.

[1]: https://github.com/cgewecke/eth-gas-reporter#options

**Comment by thedarkjester** [comment]
thanks for the quick reply - not sure why it isn't showing up in the console though. do I need to do anything specific for truffle?

**Comment by thedarkjester** [comment]
worked it out - removed the json file output and it shows in the console. so pretty. thanks for the help.
