### ISSUE TITLE
Gas prices not showing up on individual tests

### ISSUE THREAD

**Issue by Diaspar4u** [cgewecke/eth-gas-reporter#265]
Run tests. No gas result showing up next to tests (note: when i set the option to show time ONLY time shows up):
<img width="215" alt="Screen Shot 2021-11-28 at 08 12 08 PM" src="https://user-images.githubusercontent.com/3605840/143794489-f5d89879-55ca-458b-b597-be74202a3441.png">
).

I DO get the overview table after the tests..

What's missing?

My config:
```
  gasReporter: {
//    currency: "USD",
    coinmarketcap: process.env.COINMARKETCAP_KEY,
    onlyCalledMethods: true,
    enabled: true
  }
```

**Comment by cgewecke** [comment]
@Diaspar4u If you're using the hardhat plugin, only the table analysis is generated. The per-test gas consumption measurement was removed in that version to make it run much faster. 

If you want to see those numbers you can try:
+ removing the `gasReporter` object from the config
+ configuring the `mocha` object with eth-gas-reporter settings (the way it's done for truffle, see README)
+ running your tests on network `localhost` against a stand-alone client (like ganache-cli or hardhat node)
