### ISSUE TITLE
Not working properly when tests are written using Waffle

### ISSUE THREAD

**Issue by Bolee95** [cgewecke/eth-gas-reporter#267]
Hi everyone,

I'm working on a project using the Truffle framework for development, Ganache as a local network and Waffle for testing. The reason I don't use native testing for Truffle is that I find creating mocks easily a really convenient tool, and with Waffle, it doesn't require creating new contracts with almost copied logic as the original one.

I was trying to get gas usage of the methods called during unit testing using eth-gas-reporter, but I cannot generate a report with methods gas usage. However, I do get contacts deployment gas usage.

Something that I think is causing this is that I do not use artefacts generated during `truffle deploy` command. I use files with generated ABI and bytecode, as I couldn't use artefacts in combination with Waffle, which operates with Ethers.js in the background.
<img width="492" alt="Screenshot 2021-12-01 at 14 15 39" src="https://user-images.githubusercontent.com/20232629/144241003-26638b39-7c5c-4887-9d3b-c8d0adf15b7c.png">
 
<img width="496" alt="Screenshot 2021-12-01 at 14 15 34" src="https://user-images.githubusercontent.com/20232629/144241055-2bc8821e-12df-4d53-ba69-0fa10bb94297.png">

This is a report generated after running tests:
<img width="806" alt="Screenshot 2021-12-01 at 14 17 43" src="https://user-images.githubusercontent.com/20232629/144241268-c7906ebb-2d6b-4250-a945-6123d6823b56.png">

Does this ring any bell? Do I need to somehow configure the reporter differently? As you can see, the reporter is running during tests, so that's not an issue.

Would be really grateful if anyone got an answer. If you need more information, please ping me, I will provide it.

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

In the latest version at Hardhat, waffle should work as expected using the hardhat-waffle plugin

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
