### ISSUE TITLE
Terminal output corrupted

### ISSUE THREAD

**Issue by atipezda** [cgewecke/eth-gas-reporter#271]
That's the output when running `npx hardhat test` with the gas-reporter module

os: **Mac osx 12.0.1**
terminal emulator: **Iterm2**
font: **Hack Nerd Font**
shell: **zsh**

also tested with other fonts, other terminal emulators, and shells.
Running `npx hardhat test > out.txt` - redirecting output to file also does contain corrupted data

<img width="1070" alt="Zrzut ekranu 2022-01-10 o 17 17 15" src="https://user-images.githubusercontent.com/43711283/148803641-568160d4-0d6c-486c-817e-f06b681497d4.png">

**Comment by cgewecke** [comment]
This should be patched with hardhat-gas-reporter 1.0.7. Could you upgrade and verify that it resolves?

**Comment by atipezda** [comment]
Fixed in `hardhat-gas-reporter 1.0.7`
