### ISSUE TITLE
Feature request: Optimism support

### ISSUE THREAD

**Issue by andrewshvv** [cgewecke/eth-gas-reporter#273]
@cgewecke 

Hey, pretty new in web3 space, I am wondering - can the eth-gas-reporter support Optimism?

I am not familiar with eth-gas-reporter internals and thought that maybe you can give me initial guidance on what kind of changes are necessary to make it work and the place where to start looking? 

Depending on the work required I may try to implement it.

From an initial naive glance it seems we need:
- Separate `gasPrice` on `gasPriceL1`, and `gasPriceL2`.
- Separate `gasUsed` on `gasUsedL1`, and `gasUsedL2`.
- Calculate the calldata size, and derive cost based on `gasPriceL1` and `gasUsedL1`.
- Leave the rest of the cost to be based on `gasPriceL2` and `gasUsedL2`.

About Optimism fees: https://community.optimism.io/docs/developers/l2/new-fees.html#frontmatter-title

**Comment by cgewecke** [comment]
Yes, that looks right to me. 

As a practical matter this tool is most commonly run with HardhatEVM or ganache-cli (both ethereumjs-vm based) It would nice to know if gasUsedL2 on an optimism vm is reasonably similar to what is used on an L1 ethereum vm. 

Do you know if that's the case?

**Comment by cgewecke** [comment]
Cross-linking relevant issue at hardhat-gas-reporter

https://github.com/cgewecke/hardhat-gas-reporter/issues/78

**Comment by andrewshvv** [comment]
Cool, glad to hear that!

> It would nice to know if gasUsedL2 on an optimism vm is reasonably similar to what is used on an L1 ethereum VM. 
Do you know if that's the case?

By reading this it seems so https://research.paradigm.xyz/optimism 
But I will take a deeper dive in a couple of days.

> Cross-linking relevant issue at hardhat-gas-reporter
Yeah, `hardhat-gas-reporter` is what I am actually using.

Alright, I will take a look in utils.js, optimism rpc node documentation, ethereumjs-vm docs.

**Comment by andrewshvv** [comment]
If we have any trouble getting the proper values to calculate the L1 gas cost I believe we can do the estimation similar to this:
https://dune.xyz/queries/276487

**Comment by smartcontracts** [comment]
FYI, we just updated the Optimism docs to give more information about how to accurately estimate the current L1 data cost for a given transaction: https://community.optimism.io/docs/developers/build/transaction-fees/#estimating-the-l1-data-fee

**Comment by smartcontracts** [comment]
When computing the total cost for a transaction on Optimism you need to account for two things, the L2 "execution" fee and the L1 "data" fee.

The L2 execution fee can be computed with the standard formula of `provider.estimateGas(tx) * provider.getGasPrice()`.

The L1 data fee can be most easily estimated by making a query to `OVM_GasPriceOracle.getL1Gas(serialize(tx))`.

**Comment by andrewshvv** [comment]
First calculation:
<img width="1195" alt="Screen Shot 2022-01-24 at 6 29 43 AM" src="https://user-images.githubusercontent.com/3414579/150718004-b7dc6be5-73fa-4555-9ed4-7d4ecef2ea19.png">

**Comment by math77** [comment]
this was implemented?

**Comment by andrewshvv** [comment]
@math77 nah, sorry, never got it working properly
it is open for anyone to take

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

In the latest version at Hardhat, Optimism Ecotone l1GasUsed and total cost are available by setting the `L2` option to "optimism". The reporter synthesizes these costs locally so there's no performance hit for collecting this data while running your tests.

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
