### ISSUE TITLE
@ethersproject/abi minimum version is too low

### ISSUE THREAD

**Issue by aprothman** [cgewecke/eth-gas-reporter#276]
The minimum required version of @ethersproject/abi is currently set to "^5.0.0-beta.146". Starting in ethers 5.2, the ABI parser was first able to parse solidity's custom error objects. eth-gas-reporter fails process test output for methods that include custom errors if the installed version of @ethersproject/abi is below 5.2. In order to support modern solidity code, the minimum version should be updated to at least 5.2.

**Comment by cgewecke** [comment]
Apologies for this, fixed in 0.2.27
