### ISSUE TITLE
app/assets/v2/js/cart.js

### ISSUE THREAD

**Issue by jeffreysmooths** [cgewecke/eth-gas-reporter#278]
https://github.com/jeffreysmooth/Hokopokos--Superdata/issues/2#issue-1091761907

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
