### ISSUE TITLE
Joinme

### ISSUE THREAD

**Issue by jeffreysmooths** [cgewecke/eth-gas-reporter#280]
https://t.me/cebturyoftruth

**Comment by cgewecke** [comment]
@jeffreysmooths If you're real could you stop opening issues here? Thanks.

**Comment by jeffreysmooths** [comment]
> @jeffreysmooths If you're real could you stop opening issues here? Thanks.
  
Please why have I been asked to stop opening issues here , please enlighten if I may be doing something wrong ,I'm only trying to explore

**Comment by cgewecke** [comment]
The issues and PRs you're opening report nothing and/or do nothing. I thought you were a bot actually. What exactly are you hoping to achieve with your current contributions?

**Comment by jeffreysmooths** [comment]
> The issues and PRs you're opening report nothing and/or do nothing. I thought you were a bot actually. What exactly are you hoping to achieve with your current contributions?

I'm new here not been up to a month or probably a month I opened this I lost the private key to my xlm wallet and I've been try to open issues that could help me retrieve such info

**Comment by cgewecke** [comment]
Stay out of github repos with this stuff please. Period.
