### ISSUE TITLE
Change Int to Float for gas gwei representation

### ISSUE THREAD

**Issue by tempest-sol** [cgewecke/eth-gas-reporter#283]
https://github.com/cgewecke/eth-gas-reporter/blob/27ba98a23b6fc4d4deaebed7aff6e284791781c9/lib/codechecksReport.js#L41

Arbitrum L2 gas is currently under 1, at 0.38, by default this parses as integer 0 (rounding down), thus making the gas reported show nothing as the cost.

Suggestion:
Change parseInt to parseFloat to allow these scenarios.

**Comment by thegreat-vanderlinde** [comment]
+1 on this

**Comment by cgewecke** [comment]
Hi! `eth-gas-reporter` is being deprecated in favor of `hardhat-gas-reporter`. 

In the latest version at Hardhat, sub-gwei gas prices are fully supported:

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
