### ISSUE TITLE
eth-gas-reporter  not working on Macbook Pro 2021, 14 inch, Error: truffle-plugin.json not found in the eth-gas-reporter plugin package!

### ISSUE THREAD

**Issue by muneebzubairkhan** [cgewecke/eth-gas-reporter#284]
eth-gas-reporter is not making a table with gas used at the end of test. I used "truffle test" and test were run but no table and the end.

**Comment by cgewecke** [comment]
@muneebzubairkhan Which version of truffle are you using?

Could you see if running `truffle test --reporter eth-gas-reporter` results in a table being generated?

**Comment by cgewecke** [comment]
Closing, stale
