### ISSUE TITLE
compiler optimization & runs

### ISSUE THREAD

**Issue by Gr3it** [cgewecke/eth-gas-reporter#286]
I can't find anywhere how to change the compiler settings for the test, I want to run the test with optimization enabled and set the run parameter. I'm using it in hardhat and the compiler setting in the config file do nothing.

**Comment by cgewecke** [comment]
@Gr3it Are you sure you're configuring it correctly? The gas reporter just reads the information from hardhat. Hardhat's compiler config docs are here: 

https://hardhat.org/guides/compile-contracts.html#configuring-the-compiler.

Could you give an example of a compiler config which works but isn't being correctly reported in this plugin's output?

**Comment by Gr3it** [comment]
Yes, my bad. I was using the hardhat tutorial config option that was   

  solidity: "0.8.11",
  settings: {
    optimizer: {
      enabled: true,
      runs: 200,

instead of the docs one

  solidity: {
    version: "0.8.11",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },

**Comment by cgewecke** [comment]
Ok I will close here then.
