### ISSUE TITLE
Should have an option to switch between type-2 (EIP-1559) txs and legacy transactions

### ISSUE THREAD

**Issue by blockchainguyy** [cgewecke/eth-gas-reporter#291]
My apologies if this config option is already present but if not I think we should add it in an eth gas reporter.

**Comment by cgewecke** [comment]
Hi! eth-gas-reporter is being deprecated in favor of hardhat-gas-reporter.

In the latest version, this issue is being tracked at https://github.com/cgewecke/hardhat-gas-reporter/issues/194

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
