### ISSUE TITLE
Doesn't work with truffle develop

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/eth-gas-reporter#42]
On `4.0.0-beta.2` the tests don't execute and an empty table is printed.

On `4.0.1` mocha reports reporter not found:
```
truffle(develop)> test
"eth-gas-reporter" reporter not found
Error: invalid reporter "eth-gas-reporter"
```

Tried installing the reporter globally and got the same error.

**Comment by clesaege** [comment]
I also get the same issue.

**Comment by M1kep** [comment]
@clesaege Do you have both mocha and eth-gas-reporter installed in the same scope? I had this issue until I made sure mocha and eth-gas-reporter were installed globally, or locally.

**Comment by cgewecke** [comment]
@M1kep Interesting! Great, that's good to know.
