### ISSUE TITLE
Enabling this reporter severely decreases the ability to debug failing tests

### ISSUE THREAD

**Issue by roderik** [cgewecke/eth-gas-reporter#44]
Without this reporter, a failing test will print out the error messages as soon as the run finishes. Was it a revert, a opcode or invalid jump, etc. Stuff that really helps figuring out the issue.

With the reporter, it does no longer print out these errors. Which means that I can use it as long as my tests all pass, but as soon as one fails, I have to disable it to fix it.

**Comment by cgewecke** [comment]
@roderik Thanks, this might be a helpful clue to what is going wrong in #19 as well. Investigating....

**Comment by cgewecke** [comment]
@roderik This should be fixed with `0.0.14`. Please feel free to re-open if you still see this problem and thanks again for reporting.
