### ISSUE TITLE
Colors should be optional

### ISSUE THREAD

**Issue by rmuslimov** [cgewecke/eth-gas-reporter#51]
There is no way now to switch off colors.

**Comment by cgewecke** [comment]
Agree, especially useful if you are printing a report as in #53. Haven't tried this but in the colors code [here](https://github.com/Marak/colors.js/blob/master/lib/colors.js#L103) it looks possible to toggle an enabled flag to false on the object.

**Comment by cgewecke** [comment]
With #57 there is a `noColors` option which suppresses colorization in the report. The only way I was able to get the entire test output to be color free was by setting the option AND setting a `--no-colors` cli flag to true for Node. e.g:
```sh
./node_modules/.bin/truffle test --no-colors
```

**Comment by cgewecke** [comment]
Published in `0.1.1`
