### ISSUE TITLE
Filtering out unused contract methods

### ISSUE THREAD

**Issue by rmuslimov** [cgewecke/eth-gas-reporter#54]
It is possible that a lot of methods implemented in contracts will be not covered (for different reasons: small coverage, optional tests called, etc.). For those cases, I think having only called Methods in table desirable.
Let's have this as an option in .ethgas.js

**Comment by rmuslimov** [comment]
Please consider #56 as solutino

**Comment by cgewecke** [comment]
#56

**Comment by cgewecke** [comment]
Published in `0.1.1`
