### ISSUE TITLE
Mocha has own implementation of parameters for reporters

### ISSUE THREAD

**Issue by rmuslimov** [cgewecke/eth-gas-reporter#55]
Subj. Why using `.ethgas.js` needed? Parameters are stored under `reporterOptions`
For example: https://github.com/michaelleeallen/mocha-junit-reporter

**Comment by cgewecke** [comment]
Cool, this is worth looking into.  For some reason the fact that an options object is passed to the reporter is not documented at Mocha. . .

**Comment by cgewecke** [comment]
Thanks for opening this: mocha's `reporterOptions` is the default with `0.1.1`.
