### ISSUE TITLE
To get the Dispaly of gas Used for each transaction 

### ISSUE THREAD

**Issue by tbenny** [cgewecke/eth-gas-reporter#77]
I Installed eth-gas-reporter and npm install -g eth-gas-reporter
How can I get the gas report  from the terminal

**Comment by cgewecke** [comment]
@tbenny Hi. I just tried with global install and it seems like it's having trouble finding the reporter that way. In your truffle project, will you try running:
```shell
npm init # <-- Only if you don't already a local `node_modules` in the project. 
npm install --save-dev eth-gas-reporter
```
And then in your `truffle.js`, add a mocha config key:
```javascript
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  mocha: {
   reporter: 'eth-gas-reporter',
 }
};
```

**Comment by tbenny** [comment]
I did as per your recommendation , but after truffle migrate , i am not getting any report sort of thing.K indly help

**Comment by cgewecke** [comment]
@tbenny Apologies, this report is only produced when you run `truffle test`. If you `new` contracts within your tests the chart will contain data for those deployments, e.g:
```
const instance = await myContract.new();
```
