### ISSUE TITLE
Test stop at string.match(regex) when a certain contract is in the test

### ISSUE THREAD

**Issue by ben-kaufman** [cgewecke/eth-gas-reporter#85]
Hey there,

I am trying to connect the reporter to daostak/arc (https://github.com/daostack/arc) but for some reason, the test just stops.
We tried to debug it and found that this line causes the reporter operation to stop:
``const regExp = new RegExp(`^${binary}`);`` at getStats.js line 76.
This only happens when the UController.sol contract is in the project when we remove this contract the reporter starts to work again.

Would appreciate any help on the matter.

**Comment by cgewecke** [comment]
Thanks for opening @ben-kaufman 

Think issue might be that the binary is larger than the maximum allowed size for a regex? Saw this come up in some other code that binary matches recently [here](https://github.com/maticnetwork/sol-trace/blob/master/src/web3-trace-provider.js#L269-L272). 

Will fix this weekend (unless you would like to open a PR w/ logic similar to the one in the link before then).

**Comment by ben-kaufman** [comment]
Thanks! Just created a PR for that.
