### ISSUE TITLE
Report table doesn't count calls for other contracts

### ISSUE THREAD

**Issue by ben-kaufman** [cgewecke/eth-gas-reporter#91]
I have a bug with the report table, it displays incorrect gas usage. I have a contract which in one of its functions calls the decreaseApproval function of a StandardToken contract (https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/StandardToken.sol) and fires an event.
The cost which the table displayed for calling that function was 22,204, this is about the cost of the basic tx fee and a single event, it looks like it didn't count the call to the other contract at all.

**Comment by cgewecke** [comment]
@ben-kaufman Adding a test for this in #93 and it seems like it works? I've created a method (`otherContractMethod`) that calls another contract storing a uint to the same slot 3 times and the total cost is 57,000. Which seems *about* right . . . not sure.
```
21,000 # fn call
20,000 # storage to uninitialized location
5,000 # write to storage at initialized location
5,000  # write to storage at initialized location
```

If you have a chance, could you take a look at the test case in #93 and see if there's an obvious difference from your method?

**Comment by cgewecke** [comment]
Occurs to me you might be getting a refund by setting storage to zero with `decreaseApproval`. Is that possible?

**Comment by ben-kaufman** [comment]
I think you're right, I didn't note that the test I did decrease all the approval thus changed the storage to 0.
Sorry for the mistake and thanks for your help.
