### ISSUE TITLE
Incompatible with truffle-hdwallet-provider

### ISSUE THREAD

**Issue by 4000D** [cgewecke/eth-gas-reporter#95]
When using truffle-hdwallet-provider, eth-gas-reporter doesn't work with this below error.

```bash
TypeError: Cannot read property 'url' of undefined
    at Object.request (/Users/pjh/workspace/Sweeper/node_modules/eth-gas-reporter/sync.js:49:10)
```

https://github.com/cgewecke/eth-gas-reporter/blob/8d9e5465477e7bbddf9be1add27ef853cde4d201/sync.js#L44-L51

there is no `connection` for truffle hdwallet provider.

**Comment by cgewecke** [comment]
@4000D Yes that's correct. The gas reporter needs to make some calls synchronously and truffle-hdwallet-provder (through web3-provider-engine) doesn't allow that. Will put a note in the README about this and try to improve the error detection at that location in the code too.

**Comment by wighawag** [comment]
I created a pull request that fallback on the Spec reporter if the web3 provider do not support sync call : https://github.com/cgewecke/eth-gas-reporter/pull/101

This way you can still run your test with in memory ganache
And then if you want to get the gas report, you run it with external ganache

**Comment by cgewecke** [comment]
#101
