### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by morrigan** [cgewecke/eth-gas-reporter#99]
By repeating tests couple times I've noticed that almost all functions have different results in each report so I am wondering what might the reason for that be.

For example, here are the results for one function from 4 runs with the same tests:
```
 MIN     ·   MAX   ·    AVG
288769  ·  336209  ·  301035  
288769  ·  428377  ·  307880 
288769  ·  335911  ·  300365
288769  ·  393734  ·  306867 
```

Number of calls is the same and params in tests are always the same. Any possible reason for this outputs?

Test files are long and complex so I won't post them here if that's ok :)

**Comment by morrigan** [comment]
Unfortunately, it's not open sourced now so I can't share but I will try to investigate more. To answer your questions:

- In some tests I use hashing block variables like timestamp but that's not the case in all functions that have this issue. Not sure what you mean by state being reverted but I create new instance of a struct on each test so they should not affect each other. 
- Ganache
- No, not using oracles.

If this is not the usual problem then definitely I'll try to look more into it.

**Comment by cgewecke** [comment]
@morrigan 
> Not sure what you mean by state being reverted but I create new instance of a struct on each test so they should not affect each other.

Ok, that should be fine. . .if they did somehow share state and you were setting and then zeroing out storage values you might be getting gas refunds that would vary the results. Truffle will revert the entire blockchain state between `contract` suites. But it sounds like you might be seeing different results between test runs anyway . . . 

In any case it *could* be a bug here - if you have a chance to generate a reproduction case for this that would be great.

**Comment by morrigan** [comment]
Ok, I think this might be a false alarm :D I do have a "random" element in those tests so it's probably it. Not sure how I didn't notice it right away 😶
